### ISSUE TITLE
Building requires sudo

### ISSUE THREAD

**Issue by slundberg** [JuliaInterop/ZMQ.jl#137]
When trying to `Pkg.build("ZMQ")` on a shared linux server the process crashed because it was trying to run `sudo yum install czmq`

```
julia> Pkg.build("ZMQ")
INFO: Building ZMQ
Installing dependency czmq via `sudo yum install czmq`:
=====================================[ ERROR: ZMQ ]=====================================

LoadError: could not spawn `sudo yum install czmq`: no such file or directory (ENOENT)
while loading ~/.julia/v0.5/ZMQ/deps/build.jl, in expression starting on line 35
```

Requiring root access to use this seems like a bad idea.

For anyone else with this issue just comment out the line `provides(Yum, "czmq", zmq, os = :Linux)` in `~/.julia/v0.5/ZMQ/deps/build.jl` which will force it to download and build from source and not try to use yum.

**Comment by JonathanAnderson** [comment]
Thanks. I'm not in my cluster's sudoers so I was comping here for this very issue.

**Comment by maxeywen** [comment]
Also here for this same issue.  Fedora 25.  except my load error reads

LoadError: failed process: Process(`sudo yum install czmq`, ProcessExited(1)) [1]
while loading /home/maxwen/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 35
