### ISSUE TITLE
get_events slows down send, can it be moved or removed?

### ISSUE THREAD

**Issue by ggggggggg** [JuliaInterop/ZMQ.jl#142]
See [this thread for context](https://discourse.julialang.org/t/zmq-message-super-slow/3193/5). I made a version of `send` (`sendfast` below) that removed `get_events`. When I benchmark vs send as follow
```julia
m=Message("1")
@benchmark send(s,m)
@benchmark ZMQ.sendfast(s,m)
```
I find that the time per `send` is about 1.5 us, and the time per `sendfast` is about 0.1 us, so about 15 times faster for small message. If I simply redefine `send` with `get_events` removed, all the tests pass. So I'm wondering if `get_events` can just be removed and I'm guessing the answer is no. To demonstrate that, it would be great to have a test that fails is `get_events` is removed. 

If it can't be removed, should `sendfast` or something like it be defined?

```julia 
function sendfast(socket::Socket, zmsg::Message, SNDMORE::Bool=false)
  while true
      rc = ccall((:zmq_msg_send, zmq), Cint, (Ptr{Message}, Ptr{Void}, Cint),
                  &zmsg, socket.data, (ZMQ_SNDMORE*SNDMORE) | ZMQ_DONTWAIT)
      if rc == -1
          zmq_errno() == EAGAIN || throw(StateError(jl_zmq_error_str()))
          while (get_events(socket) & POLLOUT) == 0
              wait(socket)
          end
      else
          #get_events(socket) != 0 && notify(socket)
          notify(socket)
          break
      end
  end
end
```

**Comment by vtjnash** [comment]
As the git-blame-ee, we can see that the call is a performance optimization (https://github.com/JuliaInterop/ZMQ.jl/commit/393cbfa6f036670d6d86e50a6f9eff6df1d43e32#diff-242ae582b15ae751f625b09f8d72a192L620)

Nice performance sleuthing, it looks like it needs some more optimization work...

I think the right approach here would be to first call `!isempty(socket.pollfd.notify.waitq)` to see whether the `notify` will be expensive (making the get_events call worthwhile) or a no-op (making it wasteful). Would you be able to submit a PR?

**Comment by ggggggggg** [comment]
Looks like you're right

```julia
using ZMQ, BenchmarkTools
import ZMQ: zmq,ZMQ_SNDMORE, ZMQ_DONTWAIT, POLLOUT, get_events, zmq_errno, jl_zmq_error_str
ctx = Context()
socket = Socket(ctx, PUB)

m = Message("1")

function sendmod(socket::Socket, zmsg::Message, SNDMORE::Bool=false)
    while true
        rc = ccall((:zmq_msg_send, zmq), Cint, (Ptr{Message}, Ptr{Void}, Cint),
                    &zmsg, socket.data, (ZMQ_SNDMORE*SNDMORE) | ZMQ_DONTWAIT)
        if rc == -1
            zmq_errno() == EAGAIN || throw(StateError(jl_zmq_error_str()))
            while (get_events(socket) & POLLOUT) == 0
                wait(socket)
            end
        else
            notify_is_expensive = !isempty(socket.pollfd.notify.waitq)
            if notify_is_expensive
              get_events(socket) != 0 && notify(socket)
            else
              notify(socket)
            end
            break
        end
    end
end

@benchmark sendmod(socket,m)
@benchmark send(socket,m)
``` 
Gives 1.5 us for `send` and 0.09 us for `sendmod` on master. I'll submit a PR.

**Comment by vtjnash** [comment]
You don't need to call notify when it'll be a no-op

**Comment by ggggggggg** [comment]
Does that translate to "get rid of the else"?

**Comment by vtjnash** [comment]
yes :)

**Comment by ggggggggg** [comment]
Thanks for the help!
