### ISSUE TITLE
Build error in Julia 0.6

### ISSUE THREAD

**Issue by pstaabp** [JuliaInterop/ZMQ.jl#149]
I just tried to install IJulia on 0.6 and an error popped up because of ZMQ:

```
LoadError: SystemError: unable to read directory /Users/pstaab/.julia/v0.6/Homebrew/deps/usr/Library/Taps/staticfloat/homebrew-juliatranslated: No such file or directory
while loading /Users/pstaab/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 35
```

and in fact that directory does not exist.  Is this a julia-homebrew issue? 

I'm running macOS 10.12.5.

**Comment by stevengj** [comment]
Sounds like a HomeBrew.jl problem and should be reported there.
