### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by blegat** [JuliaInterop/ZMQ.jl#154]
Would it be possible to release a new version of this package ? I keep getting the warning "WARNING: Compat.AsyncCondition is deprecated, use Base.AsyncCondition instead." but I see it is fixed on master.

**Comment by stevengj** [comment]
Tagged 0.4.4

**Comment by ViralBShah** [comment]
Requested to tag ZMQ 0.5.0

https://github.com/JuliaInterop/ZMQ.jl/issues/154
