### ISSUE TITLE
ZMQ on 0.7.0-DEV

### ISSUE THREAD

**Issue by jheinen** [JuliaInterop/ZMQ.jl#159]
ZMQ can no longer be built on Julia 0.7.0-DEV.24xx, as some methods have been moved from `Base.Filesystem` to `Base.FileWatching`, e.g. `UV_READABLE`, `uv_pollcb`, `_FDWatcher`.

Are there plans to add support for the `FileWatching` module in `ZMQ`, or will this be fixed in a future version of `Compat.jl`?

Right now, `IJulia` can **not** be used with the Julia 0.7 development version.

**Comment by stevengj** [comment]
This should really be fixed in Compat, I think.

**Comment by Nosferican** [comment]
The fixes for the latest versions are:
```
import FileWatching: UV_READABLE, uv_pollcb, FDWatcher

type Socket
    data::Ptr{Void}
    pollfd::FDWatcher

    function Socket(ctx, typ::Integer)
        p = ccall((:zmq_socket, zmq), Ptr{Void}, (Ptr{Void}, Cint), ctx.data, typ)
        if p == C_NULL
            throw(StateError(jl_zmq_error_str()))
        end
        socket = new(p)
        socket.pollfd = FDWatcher(fd(socket), #=readable=#true, #=writable=#false)

**Comment by amellnik** [comment]
I'm seeing a different error on 0.7-dev which may be windows-specific.  It looks like a shell command is not being properly escaped (see the last argument below):

```julia
LoadError: failed process: Process(`'C:\Users\amellnik\AppData\Local\Julia-0.7.0-DEV\bin\7z.exe' x -y 
  'C:\Users\amellnik\.julia\v0.7\WinRPM\cache\2\noarch%2Fmingw64-libwinpthread1-5.0.3-
  1.2.noarch.cpio' '-oC:\Users\amellnik\.julia\v0.7\WinRPM\deps'`, ProcessExited(2)) [2]
in expression starting at C:\Users\amellnik\.julia\v0.7\ZMQ\deps\build.jl:36
```

The file does exist in that location.  Let me know if I should open a separate issue.

**Comment by jheinen** [comment]
I think that's a different issue, probably a mixture of `'\'` and `'/'` directory delimiters in the `cpio` filename ...

Can check this on my Windows box tomorrow.

**Comment by jheinen** [comment]
@Nosferican : same for me, IJulia keeps restarting the kernel

**Comment by amellnik** [comment]
Just to follow up -- JuliaLang/BinDeps.jl#344 does not fix this and the problem also occurs with Pkg3.

**Comment by stevengj** [comment]
This should be fixed now, I think.
