### ISSUE TITLE
Jupyter Terminal Keeps dying 

### ISSUE THREAD

**Issue by cpar8566** [JuliaInterop/ZMQ.jl#160]
Hi, all. I am quite new to jupyter notebook. I have previously installed julia and have never used it since and I have recently taken the upgrade process. 

When I start jupyter notebook both by anaconda or julia terminal, it opens up fine and everything works fine until when i try using pyplot, the kernel suddenly dies. 

<img width="1173" alt="screen shot 2017-11-28 at 3 41 02 am" src="https://user-images.githubusercontent.com/18750943/33278032-6542e47c-d3ee-11e7-9ff9-e984bd780183.png">
<img width="1004" alt="screen shot 2017-11-28 at 3 41 31 am" src="https://user-images.githubusercontent.com/18750943/33278034-659631d6-d3ee-11e7-96ab-668fd3d14fbb.png">
<img width="646" alt="screen shot 2017-11-28 at 3 41 58 am" src="https://user-images.githubusercontent.com/18750943/33278036-65eef51e-d3ee-11e7-9a3b-73cee3023439.png">

I have been on this issue for a very long time, tried deleting python, julia and anaconda and reinstalled everything but still the same issue. 

Anyone please help!!!!!!!!!!!!

**Comment by stevengj** [comment]
Please don't file the same problem on multiple packages; seems to be a dup o JuliaLang/IJulia.jl#600

(You could try deleting `~/.julia` force Julia to re-install all of your packages.)
