### ISSUE TITLE
Homebrew removed zeromq@3.2 (for Mac installation)

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaInterop/ZMQ.jl#164]
Homebrew has recently removed the zeromq@3.2 from their formulas, which is causing the error on the installation for Mac. FYI.
https://github.com/Homebrew/homebrew-core/pull/23083

**Comment by stevengj** [comment]
We should just update to a newer version, I guess?

**Comment by hayatoikoma** [comment]
Alternatively, if the update to a newer version requires a lot of work, we can also make and maintain a tap of the version 3.2 for Homebrew.

Since I am not familiar with zeromq and the inside of ZMQ.jl, I may not be a right person to solve this issue.

**Comment by stevengj** [comment]
Upgrading ZMQ.jl to use a newer version should be less work, and is the right thing to do in the long run.

**Comment by rhsciss** [comment]
I am having this problem too. Is there a work around, while we wait for a fix?

**Comment by hayatoikoma** [comment]
I am using zeromq (version 4.2.3) that I can install with Homebrew and still haven't had any problems. I don't know the coverage of test, but, at least, the test passes with version 4.2.3.
