### ISSUE TITLE
Error in building ZMQ.

### ISSUE THREAD

**Issue by TAUFEEQ1** [JuliaInterop/ZMQ.jl#182]
Pkg.build("ZMQ")
INFO: Building ZMQ
Info: Downloading https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/ZMQ/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz...
[22:51:47] ######################################################################## 100.0%
[22:51:47] curl: (35) gnutls_handshake() failed: Error in the pull function.
=============================================================================[ ERROR: ZMQ ]=============================================================================

LoadError: Could not download https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /home/nsamba/.julia/v0.6/ZMQ/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz
while loading /home/nsamba/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 44

========================================================================================================================================================================

============================================================================[ BUILD ERRORS ]============================================================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /home/nsamba/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================================================

**Comment by stevengj** [comment]
Github was down for a while yesterday, maybe try it again?

**Comment by TAUFEEQ1** [comment]
I just reinstalled julia. I think you should too.
