### ISSUE TITLE
rcvtimeo values not honored by recv

### ISSUE THREAD

**Issue by caffeine-overload** [JuliaInterop/ZMQ.jl#198]
It seems like regardless of the value for `rcvtimeo` set, `recv` is waiting for a message for ever. 

## Example

With a local PUB socket already set up:

    using ZMQ

    s1 = Socket(SUB)
    s1.rcvtimeo = 5000

    connect(s1, "tcp://localhost:5000")
    subscribe(s1, "HHHHH") # a topic that never gets published to
    a = recv(s1, String)

## Expected behavior

recv gives up after 5 seconds

## Actual behavior

recv hangs

## More info

Using Julia Version 1.1.0

Calling `msg_recv` without the ZMQ_DONTWAIT flag, i.e. requesting blocking mode from zeromq,  results in desired behavior. Although obviously you then don't have the convenience functions like `recv(socket::Socket, ::Type{T})`. 

Maybe having an optional argument in `recv` to not use the ZMQ_DONTWAIT flag could be a simple fix for the moment.

**Comment by vtjnash** [comment]
Duplicate of https://github.com/JuliaInterop/ZMQ.jl/issues/87

**Comment by vtjnash** [comment]
I'm not sure what that field is for, but in general Julia is designed to give you synchronous options with lightweight Tasks so that you don't need to manage these timeouts manually.

**Comment by caffeine-overload** [comment]
> I'm not sure what that field is for

You mean `ZMQ_DONTWAIT`?

**Comment by vtjnash** [comment]
`s1.rcvtimeo`

**Comment by caffeine-overload** [comment]
If ZMQ_DONTWAIT is not used, msg_recv will wait for up to `rcvtimeo` milliseconds for a message to arrive. If one doesn't, it will return and set the `EAGAIN` error. 

Even if there is a way to emulate this in julia using tasks, I still think the functionality in zmq itself should be made available. I also don't believe Julia yet has a reliable way to terminate an overrunning task easily.

**Comment by caffeine-overload** [comment]
I made my own function to suit my (very simple - just a script that receives and handles values - but I know that messages arrive at least every <x> milliseconds, so a timeout indicates a dead connection) particular use case, I'm just leaving it here in case anyone else has a similar use case. 

    function zmq_receive(socket::ZMQ.Socket)::Union{String, Missing}
        zmsg = ZMQ.msg_init()
        status = ZMQ.msg_recv(socket, zmsg, 0)
        if status == -1
            if ZMQ.zmq_errno() == ZMQ.EAGAIN
                @warn "Socket timeout"
                return missing
            else
                throw(StateError(ZMQ.jl_zmq_error_str()))
            end
        end
        return ZMQ.unsafe_copy(String, zmsg)
    end

This functions honors  rcvtimeo, but probably will block a task without letting julia switch to a different one
