### ISSUE TITLE
Zeromq introductory examples

### ISSUE THREAD

**Issue by aviks** [JuliaInterop/ZMQ.jl#2]
Port over the examples from https://github.com/aviks/julia-zmq-mongrel/tree/master/examples to the new api. 

Submit them for inclusion on zeromq.org

**Comment by jchassoul** [comment]
Hi there, I submit some Julia examples to the zguide, I'm planning to submit chapter two early next week,   I just see this issue open lurking around, so please feel free to check it out and close this if you think are good introductory examples, also if you consider that I can improve the code/examples in any way please let my know and I can make the adjustments. (=

https://github.com/imatix/zguide/tree/master/examples/Julia

**Comment by ViralBShah** [comment]
Closed in #225.
