### ISSUE TITLE
make get and set more Julian, and work with v2

### ISSUE THREAD

**Issue by stevengj** [JuliaInterop/ZMQ.jl#20]
Would be nicer to have `get` and `set` defined regardless of the ZMQ version, and just throw an error if the functionality is not supported.  (Presumably, in ZMQ v2, `get(msg, ZMQ.MORE)` could just return 0 always, whereas trying to set the MORE flag to `true` would throw an exception).

However, it would be more Julian to use `ref` and `assign` for these functions, and to return the appropriate types.  i.e. you should be able to do `msg[ZMQ.MORE]` to get the `ZMQ_MORE` property (returning a `Boolean`), and `msg[ZMQ.MORE] = true` to set it.   (`ZMQ.MORE` would be a singleton type, so Julia would know how to dispatch this).

Actually, once [Julia issue #1974](https://github.com/JuliaLang/julia/issues/1974) is fixed (@JeffBezanson tells me he is working on this), one could do `msg.more` etcetera, which would be the ideal Julian syntax.

**Comment by JamesWrigley** [comment]
I'm gonna close this because we now support `getproperty()/setproperty!()` for all the Socket/Context/Message options, and we require ZMQ v4 so I don't think we need to worry about supporting multiple ZMQ versions.
