### ISSUE TITLE
Antivirus hit during package install

### ISSUE THREAD

**Issue by pticrix** [JuliaInterop/ZMQ.jl#207]
Probably a false positive.

```
julia> Pkg.add("ZMQ")
  Resolving package versions...
  Installed Artifacts ─── v1.3.0
  Installed ZeroMQ_jll ── v4.3.2+5
  Installed JLLWrappers ─ v1.1.2
  Installed ZMQ ───────── v1.2.1
Downloading artifact: ZeroMQ
Exception lors de l'appel de «DownloadFile» avec «2» argument(s): «Une exception s'est produite lors d'une requête WebClient.»
Au caractère Ligne:12 : 1
+ $webclient.DownloadFile("https://pkg.julialang.org/artifact/a3a4de5d2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
Updating `C:\Users\xarga\.julia\environments\v1.5\Project.toml`
  [c2297ded] + ZMQ v1.2.1
Updating `C:\Users\xarga\.julia\environments\v1.5\Manifest.toml`
  [56f22d72] + Artifacts v1.3.0
  [692b3bcd] + JLLWrappers v1.1.2
  [c2297ded] + ZMQ v1.2.1
  [8f1865be] + ZeroMQ_jll v4.3.2+5
```

The WebClient error is due to my AV blocking the connexion : 
![julia_urlik](https://user-images.githubusercontent.com/48171007/96636692-a6346c00-12eb-11eb-9ed8-428277b3f4d2.JPG)

I could not find any information regarding the URL/Urlik.G menace, however.

**Comment by stevengj** [comment]
This is not specific to ZMQ.jl; apparently your antivirus is blocking the Julia package system from downloading binaries.  I would suggest raising this on https://discourse.julialang.org/ to discuss what the best workaround is.

**Comment by pticrix** [comment]
Will do. However the only package that gets this hit is the ZMQ package. Good to know there's nothing wrong with it though!
