### ISSUE TITLE
Has someone deleted the https://github.com/JuliaInterop/ZMQBuilder repo?

### ISSUE THREAD

**Issue by mcgillij** [JuliaInterop/ZMQ.jl#228]
We are now getting when trying to build/install zmq.

```#12 39.65 INFO: Building ZMQ
#12 41.59 Info: Downloading https://github.com/JuliaInterop/ZMQBuilder/releases/download/v4.2.5+6/ZMQ.x86_64-linux-gnu.tar.gz to /root/.julia/v0.6/ZMQ/deps/usr/downloads/ZMQ.x86_64-linux-gnu.tar.gz...
#12 41.77 [17:36:07] curl: (22) The requested URL returned error: 404```

**Comment by stevengj** [comment]
You no longer need the ZMQBuilder repo — it's now built through [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil), and you can install the binary in Julia via `ZeroMQ_jll` (which is installed automatically by ZMQ.jl).

What are you trying to do?

**Comment by mcgillij** [comment]
We have an application that is built on julia 0.6, that recently started failing to build in our CI env, that was pulling in ZMQ from that builder repo. It's looking like we will finally have to upgrade it.

**Comment by stevengj** [comment]
Sorry about that.  If you build libzmq yourself, you could easily patch ZMQ.jl to link to whatever build of `libzmq` you want

**Comment by tkelman** [comment]
Generally better to use the github archive feature on out-of-date stuff, vs outright deleting it

**Comment by ViralBShah** [comment]
I think that was me. Sorry about that. We generally got rid of a bunch of these old Builder scripts when we moved to Yggdrasil several years ago.

**Comment by sbchisholm** [comment]
> I think that was me. Sorry about that. We generally got rid of a bunch of these old Builder scripts when we moved to Yggdrasil several years ago.
> 
> I don't see a way to restore the repo in my deleted repos. Any ideas how to restore it? Can one email github support?

@ViralBShah I'm assuming you did, but did you try the step outlined here? https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository#restoring-a-deleted-repository-that-was-owned-by-an-organization

**Comment by ViralBShah** [comment]
Yeah, that doesn't help:

<img width="917" alt="Screenshot 2024-05-23 at 9 46 05 AM" src="https://github.com/JuliaInterop/ZMQ.jl/assets/744411/022f0060-3b92-4fe9-96b6-d0438d26f118">

**Comment by JamesWrigley** [comment]
Unfortunately it doesn't seem like there's anything we can do here, short of anyone having a recent clone of the repo to recreate it :\ I'll close this but keep the issue pinned so it's visible to anyone looking for it.

**Comment by mcgillij** [comment]
I was at least able to pull a binary from the way back machine, which for now at least unblocked our build, and we can plan out an update, thanks.
