### ISSUE TITLE
Missing source file for ZMQ

### ISSUE THREAD

**Issue by Krisslon** [JuliaInterop/ZMQ.jl#251]
![2024-10-09_09-25-36](https://github.com/user-attachments/assets/c143dcc9-bee9-4f5a-8f22-1a7325224c28)

**Comment by JamesWrigley** [comment]
Looks related to this issue: https://github.com/JuliaLang/julia/issues/53623
Could you try some of the suggestions in there and see they help? In particular running PkgFsck.jl might be a good place to start: https://github.com/JuliaLang/julia/issues/53623#issuecomment-1980747789

**Comment by Krisslon** [comment]
> Looks related to this issue: [JuliaLang/julia#53623](https://github.com/JuliaLang/julia/issues/53623) Could you try some of the suggestions in there and see they help? In particular running PkgFsck.jl might be a good place to start: [JuliaLang/julia#53623 (comment)](https://github.com/JuliaLang/julia/issues/53623#issuecomment-1980747789)

![Uploading 2024-10-09_11-13-02.png…]()

**Comment by Krisslon** [comment]
> Looks related to this issue: [JuliaLang/julia#53623](https://github.com/JuliaLang/julia/issues/53623) Could you try some of the suggestions in there and see they help? In particular running PkgFsck.jl might be a good place to start: [JuliaLang/julia#53623 (comment)](https://github.com/JuliaLang/julia/issues/53623#issuecomment-1980747789)

![2024-10-09_11-13-02](https://github.com/user-attachments/assets/780a1499-b23e-447a-a8f9-5f2b36597636)

**Comment by JamesWrigley** [comment]
It looks like the package isn't registered so you'll need to install it directly from the repo: `Pkg.add(; url="https://github.com/KristofferC/PkgFsck.jl.git")`
