### ISSUE TITLE
messaging interface is unnecessarily low-level and confusing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaInterop/ZMQ.jl#46]
The `Message` type seems very unnecessary and like it exposes a lot of dangerous and confusing low-level details about how ZMQ works internally. Why doesn't `ZMQ.send` just take a array of bytes as its second argument? Why doesn't `ZMQ.recv` just return an array of bytes? ZMQ is message-oriented and each message is just an array of bytes. If someone wants to write to a buffer and then send that, they can do exactly that – construct an `IOBuffer` object themselves and then send the bytes it contains. To be helpful, `ZMQ.send` could easily allow passing an `IOBuffer` value as its second argument. You could even expose this interface:

``` julia
ZMQ.send(s) do io
  # write stuff to io
end

ZMQ.recv(s) do io
  # read stuff from io
end
```

Is there any real reason to ever expose the `Message` type to the programmer?

**Comment by JamesWrigley** [comment]
I'm gonna close this because as of #186 we can use `send()`/`recv()` with regular Julia types without needing to bother with `Message`.
