### ISSUE TITLE
problem to move julia repo, because of `.julia\v0.3\ZMQ\deps\deps.jl`

### ISSUE THREAD

**Issue by stonebig** [JuliaInterop/ZMQ.jl#68]
Hello,

I'm trying to build a movable Ijulia+ipython, and I fall on a ZMQ module "absolute path" problem.
In the file `.julia\v0.3\ZMQ\deps\deps.jl`, there is a line 12 generated with the full 'original' directory of ZMQ:
`@checked_lib zmq "D:\\result_tests\\WinPython-32bit-3.4.2.5_build3\\settings\\.julia\\v0.3\\ZMQ\\deps\\usr\\lib\\libzmq.DLL"`

==> is this absolute path  really necessary ?

**Comment by stevengj** [comment]
@Keno, should this be a bindeps issue?

**Comment by stonebig** [comment]
I have some side effects, after fixing manually this
https://groups.google.com/forum/#!topic/julia-users/aEj2V1vdbdQ

**Comment by stonebig** [comment]
ok: side-effect was because I forgot to copy the hidden `.git` files.
The only issue to get a movable Julia/IJulia seems this non-"relative" path in `.julia\v0.3\ZMQ\deps\deps.jl`.
current state of file `D:\WinPython\basedir34\buildFlavorJulia\winpython-3.4.2\settings\.julia\v0.3\ZMQ\deps`:
````
`# Load dependencies
@checked_lib zmq "D:\\WinPython\\basedir34\\buildFlavorJulia\\winpython-3.4.2\\settings\\.julia\\v0.3\\ZMQ\\deps\\usr\\lib\\libzmq.DLL"
````
whish:
````
@checked_lib zmq ".\\usr\\lib\\libzmq.DLL"
````

**Comment by stonebig** [comment]
What is curious is it is apparently the only Julia module (that I have) using an absolute path
==> shouldn't be easy to fix ?

**Comment by stonebig** [comment]
at least on reading, it looks possible to replace a ".\\" per `Base.source_path()\\` 
in https://github.com/JuliaLang/BinDeps.jl/blob/master/src/dependencies.jl around line 832
