### ISSUE TITLE
Homebrew is expecting a compiler on 10.7

### ISSUE THREAD

**Issue by malmaud** [JuliaInterop/ZMQ.jl#92]
This came up in @stevengj 's class.

**Comment by tkelman** [comment]
That's Lion, right? cc @staticfloat and ref https://github.com/staticfloat/homebrew-juliadeps/blob/013fac4333a4fa4c179ac89e06b93e1f9b3de73c/zeromq32.rb#L11, is this an upstream issue where Homebrew isn't doing bottles for Lion any more?

**Comment by staticfloat** [comment]
Yep, Homebrew tracks only the 3 latest OSX releases, expect 10.8 to
disappear soon, probably before Christmas.

**Comment by tkelman** [comment]
Could we try Conda.jl as a backup provider? They might build dylibs that support further back.

**Comment by staticfloat** [comment]
Looks like their floor is 10.6
<http://conda.pydata.org/docs/building/environment-vars.html>, so you may
have luck with that one.
-E
