### ISSUE TITLE
Subscribe not working.

### ISSUE THREAD

**Issue by abhijithch** [JuliaInterop/ZMQ.jl#95]
I have Published through c# on a certain port, and I have verified by subscribing through C#. But when I am trying to subscribe through julia (0.3.11) on windows, using the below mentioned code : 

```
ctx = Context(2)
s1 = Socket(ctx, SUB)
ZMQ.subscribe(s1)
ZMQ.connect(s1, "tcp://127.0.0.1:50001")
msg = ZMQ.recv(s1)
```

It just hangs, am I missing something? I am not very sure if this is an issue or I am missing something. Documentation does not have examples for PUB/SUB.

**Comment by stevengj** [comment]
This works for me:
```jl
ctx = Context()

p = Socket(ctx, PUB)
ZMQ.bind(p, "tcp://127.0.0.1:50001")

s = Socket(ctx, SUB)
ZMQ.subscribe(s)
ZMQ.connect(s, "tcp://127.0.0.1:50001")

ZMQ.send(p, Message("test message"))
msg = bytestring(ZMQ.recv(s))
```
(At least from the REPL; I have some problem running in this IJulia, maybe because IJulia is already using ZMQ?  I'm not sure why there would be an interaction.)
